osx_image: xcode8
language: objective-c
script:
    - xcodebuild -project Demo.xcodeproj -scheme iOSTests           -destination 'platform=iOS Simulator,name=iPhone 6'               test  | xcpretty
notifications:
email: false
